# Generated by Django 3.2.11 on 2022-01-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
