# Generated by Django 3.2.11 on 2022-01-18 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='upload_to',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
